### ISSUE TITLE
A small edit

### ISSUE THREAD

**Issue by favna** [ihaveamac/3DS-rom-tools#1]
Figured this would be the easiest way (also because I don't have discord open rn lol). 

In extracting from cia for extracting exefsheader the command is currently 

```
3dstool -xvtf exefs exefs --exefs-dir exefs --header exefsheader.bin
```

Which is better off being 

```
3dstool -xvtf exefs exefs.bin --exefs-dir exefs --header exefsheader.bin
```

Since there cannot be a directory and file both called exefs to begin with.

**Comment by ihaveamac** [comment]
fixed it
