### ISSUE TITLE
ERROR: Open file exefs failed ERROR: the file type is mismatched

### ISSUE THREAD

**Issue by icray1** [ihaveamac/3DS-rom-tools#3]
While attempting to obtain the exefsheader by using 
```3dstool -xvtf exefs exefs.bin --exefs-dir exefs --header exefsheader.bin```
I get the error in the title. What exactly is going wrong here?

**Comment by ihaveamac** [comment]
the file might not be a decrypted exefs. did you decrypt the game?

**Comment by icray1** [comment]
I figured it out.
