### ISSUE TITLE
Can't Extract Exefs

### ISSUE THREAD

**Issue by Catonthemat9154** [ihaveamac/3DS-rom-tools#4]
i tried ctrtool --intype=exefs --exefsdir=exefsdir --decompresscode exefs.bin but didn't work.
im running 64x Windows 7

**Comment by ihaveamac** [comment]
is the exefs.bin file decrypted?

**Comment by Catonthemat9154** [comment]
yes

**Comment by Catonthemat9154** [comment]
im sure about it but how do i check

**Comment by ihaveamac** [comment]
you sure? what's the output from ctrtool? what does the header look like in a hex editor?

**Comment by Catonthemat9154** [comment]
it just says ExeFS:

**Comment by Catonthemat9154** [comment]
i tried two different codes
--decompresscode is in the CMD execute

**Comment by Catonthemat9154** [comment]
![image](https://cloud.githubusercontent.com/assets/24962998/21965141/abbb58b2-db51-11e6-9d3b-12b480b299af.png)

**Comment by ihaveamac** [comment]
please use a hex editor and show me the header (first 0x200 bytes or so). HxD is a good one for Windows if you need one.

**Comment by Catonthemat9154** [comment]
skype will be easier to communicate
add me if you have it: matis05ms

**Comment by ihaveamac** [comment]
I'd prefer not to use that, sorry.

from the looks of this so far, your file probably is not an exefs. how did you get this file?

**Comment by Catonthemat9154** [comment]
![image](https://cloud.githubusercontent.com/assets/24962998/21965167/191c9222-db52-11e6-8795-ed96f24628f1.png)

**Comment by ihaveamac** [comment]
that's not an exefs. this is a blank file.

**Comment by Catonthemat9154** [comment]
it is an .bin file

**Comment by Catonthemat9154** [comment]
exefs.bin

**Comment by ihaveamac** [comment]
.bin is a generic extension. the contents of this don't make it an exefs. how did you get this?

**Comment by Catonthemat9154** [comment]
braindump from 3ds and extracted it

**Comment by Catonthemat9154** [comment]
but there was an error at the end of the dumping.
it said that it failed to output, but every single KiB was there

**Comment by ihaveamac** [comment]
that's a braindump/\*hax issue, I'm afraid. it can't dump all games, especially digital 9.6+ (seed-encrypted) ones at the moment. I would suggest you dump your game (cart or digital) using Decrypt9WIP or GodMode9.

**Comment by Catonthemat9154** [comment]
funny thing is i have Decrypt9WIP
so now i can crap in my sd card, and try to finally dmump that game
im trying to dump PkS btw

**Comment by Catonthemat9154** [comment]
thanks for your help
