### ISSUE TITLE
Make tool (like Godmode9) that dumps to cxi!

### ISSUE THREAD

**Issue by ghost** [ihaveamac/3DS-rom-tools#5]
The title says it all!

**Comment by ihaveamac** [comment]
dumps what to cxi?

**Comment by ghost** [comment]
Games (Pokemon for example)

**Comment by ihaveamac** [comment]
from what? if it's on-system you could just use GodMode9.

**Comment by ghost** [comment]
Where like ??>??>>?(

**Comment by ihaveamac** [comment]
look under SYSNAND SD and go to your target game directory (e.g. Pokémon X: title -> 00040000 -> 00055d00 -> content), choose one of the .app files (typically the largest) and decrypt it to SD (press A, NCCH image options... -> Decrypt File (...) -> Decrypt to 0:/gm9out)
