### ISSUE TITLE
DNS Server not authoritative for zone

### ISSUE THREAD

**Issue by axcolleen** [ihaveamac/3DS-rom-tools#8]
What should I do?
![3ds tool help](https://user-images.githubusercontent.com/29446003/41751891-9e512a04-7578-11e8-8249-a0dfc0082e00.png)

**Comment by ihaveamac** [comment]
[Something could be corrupted in Windows to cause this to happen.](https://www.quora.com/I-am-using-windows-7-As-soon-as-I-type-ipconfig-the-command-prompt-is-showing-the-ERROR-DNS-Server-not-authoritative-for-the-zone-How-do-I-fix-it) Try running `sfc /scannow` from an Administrator Command Prompt.

**Comment by axcolleen** [comment]
I'll try that too. When I included ctrtool on the command it worked just fine.

**Comment by ihaveamac** [comment]
You would need to include `ctrtool` because that's what you're trying to run.

**Comment by axcolleen** [comment]
Yeah I forgot.

**Comment by axcolleen** [comment]
Yeah

**Comment by axcolleen** [comment]
Thanks for your help :)
